services:
    resource.user:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\User" ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "user_read" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "user_write" ] } ]
        tags:      [ { name: "api.resource" } ]

    resource.order:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Order" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.user.order_filter" ] ]
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "order_read" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "order_write" ] } ]
        tags:      [ { name: "api.resource" } ]

    resource.licence:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Licence" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.user.order_filter" ] ]
#            -      method:    "initNormalizationContext"
#                   arguments: [ { groups: [ "order_read" ] } ]
#            -      method:    "initDenormalizationContext"
#                   arguments: [ { groups: [ "order_write" ] } ]
        tags:      [ { name: "api.resource" } ]

    payment.listener:
        class: "AppBundle\\EventListener\\PaymentListener"
        arguments: ["@router"]
        tags:  [ { name: "kernel.event_listener", event: "api.post_create", method: "onPostCreate" } ]

    resource.user.order_filter:
        class:    "AppBundle\\Filter\\UserFilter"
        arguments: ["@security.token_storage","@doctrine"]