payment_complete:
    path:     /{orderNumber}/success
    defaults: { _controller: AppBundle:Payment:complete }

payment_cancel:
    path:     /{orderNumber}/cancel
    defaults: { _controller: AppBundle:Payment:cancel }

details:
    path:     /{orderNumber}/details
    defaults: { _controller: AppBundle:Payment:details }
