services:
     appbundle_payment_manager:
         class: AppBundle\Manager\PaypalPaymentManager
         arguments:
             - @doctrine.orm.entity_manager
             - @router
             - @payment.plugin_controller